kind: Service
apiVersion: v1
metadata:
  name: file-manager-service-cip
spec:
  type: ClusterIP
  # type: NodePort
  selector:
    app: file-manager
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000